name: Publish and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty to use current version)'
        required: false
        type: string

jobs:
  publish-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Update version if provided
      if: github.event.inputs.version != ''
      run: |
        sed -i "s/mod_version=.*/mod_version=${{ github.event.inputs.version }}/" gradle.properties

    - name: Build
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      if: startsWith(github.ref, 'refs/tags/')
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Wynn API ${{ github.ref_name }}

          Auto-generated release for version ${{ github.ref_name }}

          ### Installation
          Add this to your `build.gradle`:
          ```gradle
          repositories {
              maven {
                  name = "GitHubPackages"
                  url = uri("https://maven.pkg.github.com/hezaerd/wynn-api")
                  credentials {
                      username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                      password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
                  }
              }
          }

          dependencies {
              modImplementation "com.hezaerd:wapi:${{ steps.extract_version.outputs.VERSION }}"
          }
          ```
        draft: false
        prerelease: false

    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/wapi-${{ steps.extract_version.outputs.VERSION }}.jar
        asset_name: wapi-${{ steps.extract_version.outputs.VERSION }}.jar
        asset_content_type: application/java-archive

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/libs/*.jar
          !build/libs/*-dev.jar
